### ISSUE TITLE
Define criteria for stacks to be considered certified

### ISSUE THREAD

**Issue by kilnerm** [application-stacks/certified-stack-hub#2]
We need a clearly documented set of criteria that a stack should conform to before it can be considered for inclusion in the certified stack hub.

**Comment by kilnerm** [comment]
My initial list for this is:

1. Container must be use a Red Hat base image:

- Where possible this should be a RedHat Runtimes image.
- Should always be UBI based.

2. Container images should include RPM packages only from Red Hat Universal Base Image (UBI) repositories.

3. The following metadata must be included in the container image:

- name: Name of the image
- vendor: Company name 
- version: Version of the image 
- release: A number used to identify the specific build for this image 
- summary: A short overview of the application or component in this image
- description:  A long description of the application or component in this image 

4. No modifications should be made to content provided by Red Hat packages or layers, except for files that are meant to be modified by end users, such as configuration files.

5. The container image cannot contain any critical or important vulnerabilities, as defined at https://access.redhat.com/security/updates/classification

6. No modification, replacement or combination of the Red Hat base layer(s) should be made.

7. The container image should have less than 40 layers when uncompressed.

8. The image should always be tagged with a version other than latest.

9. The image must include software terms and conditions.

- Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory.

10. The image should not run as the root user.

11. The image should not request host-level privileges.

**Comment by arthurdm** [comment]
Thanks @kilnerm!  Those look like the exact requirements checked during Red Hat certification (we have been through a few times with WL/OL/tWAS/Operator) so definitely +1 from me.

The list I have in my head was:
* The base runtime container(s) used by the Stack *SHOULD* come from the Red Hat Registry (certification is part of that process).  If not possible, it *MUST* at least pass the Red Hat Certification.
  * The base runtime container(s) *MUST* be free of compilation tools and unnecessary packages. This can be achieved today with a multi-stage Dockerfile, which although not requirement, is highly recommended.
* The Stack *MUST* have a `stack.yaml` with template variables for key versions of the source code (e.g. POM files) and runtime containers (e.g. `FROM` in Dockerfiles).
* The Stack  *MUST* have a `app-deploy.yaml` file that specifies the deployment of its application runtime container, using either: 
  * (a) Application Stacks Operator, or 
  * (b) A runtime-specific Operator with equivalent functionality, such as the Open Liberty Operator
* The final Stack images *MUST* pass the Red Hat Certification.

**Comment by jgawor** [comment]
I would also add that stack images must support arbitrary user ids as described on
https://docs.openshift.com/container-platform/4.3/openshift_images/create-images.html#images-create-guide-openshift_create-images.

**Comment by arthurdm** [comment]
Another requirement will be in terms of multi-architecture support: for both the runtime container image(s), and the Stack image itself.

**Comment by sam-github** [comment]
"certified" by whom? IBM? RedHat?

**Comment by arthurdm** [comment]
the CP4Apps Stacks are certified by IBM.  But in that process there will be a few container images that are also certified by Red Hat.

**Comment by sam-github** [comment]
> Another requirement will be in terms of multi-architecture support: for both the runtime container image(s), and the Stack image itself.

This requires multi-arch machines capable of running the image build. Do we/will we have a recommendation on where to run the builds?

**Comment by arthurdm** [comment]
hey @sam-github - Travis has the capability to run in multi-archs (see [this doc](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z)).  

Here's one example (from our Runtime Component Operator) where the build is running in different architectures and producing a manifest on top of the 3 images: https://github.com/application-stacks/runtime-component-operator/blob/master/.travis.yml

**Comment by sam-github** [comment]
> The Stack MUST have a stack.yaml with template variables for key versions of the source code (e.g. POM files) and runtime containers (e.g. FROM in Dockerfiles).

Could you elaborate? I don't know what a POM file is. Are you saying the base FROM shouldn't be defined in, for example with appsody's Dockerfile-stack, a literal value? So, instead of `FROM node:12` (or a ubi equiv), it should be an env var. and the stack.yaml should have it? I don't understand how that would help, switching base images would likely break the Dockerfile(-stack). Definitely does with ubi to community, they have different users pre-setup.

**Comment by arthurdm** [comment]
Hey @sam-github - I've now changed the `MUST` to a `SHOULD`, so that we don't exclude frameworks that don't fit this pattern.

Basically the ability to change the `FROM` was meant more for version upgrades - for example, in Liberty there's a zero-migration policy, so you can safely upgrade your Liberty 19.0.0.12 to Liberty 20.0.0.1.  Yes, it does imply staying within the same "type" of image (i.e. not switching between Ubuntu and UBI, or choosing another variant with a different JDK for example).

**Comment by sam-github** [comment]
Sounds good. I noticed this here because I finally took a couple minutes to track down why nodejs stacks all have a lint warning, and realized it wasn't actually relevant, and the messaging is too strong -- https://github.com/appsody/appsody/pull/952

**Comment by arthurdm** [comment]
Closing this via PR #3 - will open subsequent issues.
